#+TITLE:       Developer Journal - February 2019
#+AUTHOR:      John Stevenson
#+DATE:        <2019-02-01 Fri>
#+EMAIL:       john@jr0cket.co.uk
#+LANGUAGE:    en

* 20190228 ClojureBridge user guides
** Thoughts for today
   Time to investigate the images not loading on pages hosted on Github pages.

   Finish off the user guide for VSCode and Calva. Thinking of adding Joker to the ClojureBridge install instructions as an option.

   Test the install and user guides on the Windows machines.

   Cats having a bit of a rampage today, maybe I shouldn't have fuelled them up with that string...

* 20190227 Started Calva user guide
** Thoughts for today
   Really impressed by the motivation and openness of the Calva developer (VSCode extension for Clojure/Script).  The Calva project seems to be evolving very quickly and already is a very good tool for Clojure development.


** Activities
*** Started user guide for Calva
    Discussed some of the details around the current user guide with author of the Calva extension for VSCode, the extension that is building a CIDER like experience.  The developer is very active and very responsive to questions on Slack.

    I got some updated dependencies, which are currently required to connect to a REPL run from Leiningen.  This is the currently supported way of using Calva, although there is a beta of a ~jack-in~ function that will inject these dependencies (just like CIDER).

*** New talk night for London Clojurians
    G
* 20190225 Tidying the Kitchen
** Thoughts for Today
   Took a bit of a break today and organised the kitchen better.  I bought glass steamer trays to make a ceramic and glass steamer combo for cooking my kale and other vegetables.  The metal steamers were okay, but as I am in a hard water area then limescale easily builds up on the metal.  Now I just need to donate my unused steamer.
   Bought a pot rack for my ceramic pots, to make them more accessible and take up less space in the kitchen.

* 20190224 Clojure Study group broadcast
** Thoughts for today
** Code
*** [[https://github.com/jr0cket/compojure-api-experiment-my-api/commit/2432bdeffaaa0ccf978a089e4cf6d65db4a41bc0][Compojure-api-experiments-my-api]] - first 10 commits
** Activities
*** Clojure study group broadcast - create a simple API
    Today I walked through building a simple API using the ~compojure-api~ library.

    [[https://www.youtube.com/watch?v=cZdo_vYvd8M][Recorded broadcast]]

* 20190223 More Compojure API fun
** Thoughts for today
   Worked on a ~compojure-api~ based project for the study group.  Focused on explaining what is created from the ~compojure-api~ Leiningen template with the ~+clojure-test~ option.

* 20190222 Started Compojure API fun
** Thoughts for today
   Very happy with the coach training session last night (apart from loosing my cycling gloves).  The [[https://docs.google.com/presentation/d/e/2PACX-1vR_RYp1Vq9O75hmjG-SWRjtr8zezF8CUXicIOSkJqJf-U512u9E7SZm0UCzcIxqbia1VWObchTx9e-L/pub?start=false&loop=false&delayms=3000][presentation]] is much better now and the introduction of practical exercises really engaged the volunteer coaches.  The [[https://www.youtube.com/watch?v=cZdo_vYvd8M][broadcast recording]] for the event seems to have worked too and we had at least one person on during the event.

   Org-mode doesn't seem to want to tab expand ~<s~ for a source block again.  Instead a source block can be created using ~org-bable-demark-codeblock~ or its keybinding ~, b d~.

   The Google Maps disappearing bug is still haunting me, but on only on Chrome Beta.  I cleared the cache as fixed the issue previously, I deleted cookies from the padlock in the URL so now am going to see if I can install a newer version of Chrome beta, I am currently using Version 73.0.3683.27 (Official Build) beta (64-bit).  I've downloaded version 73.0.3683.46-1 from [[https://www.google.com/intl/en_uk/chrome/beta/]].

   Have a bit of flu and coughing quite a lot by the end of the day.  Postponing the weekly Clojure study group broadcast until Sunday.
** Code
*** Status monitor: [[https://github.com/jr0cket/webapp-status-monitor/commit/006fafcd525f1c006eed361f9b222338fbabeb0a][Commented out HTML svg code for cider logo]]
*** Statue monitor: [[https://github.com/jr0cket/webapp-status-monitor/commit/77b5e6690826aff327beb9fbbf44344ed8d702aa][Added missing path of CIDER logo, changed viewbox size]]
*** compojure-api: [[https://github.com/jr0cket/compojure-api-experiment-my-api/commit/6faa2661798fc08e3e99deae0b906a745dd53030][Initial compojure-api project with clojure-test]]
*** compojure-api: [[https://github.com/jr0cket/compojure-api-experiment-my-api/commit/2432bdeffaaa0ccf978a089e4cf6d65db4a41bc0][Documentation and formatting]]
** Activities
*** Status monitor: fixed the build and added path to cider logo
    I broke the CircleCI build as I neglected to comment the HTML SVG code for the cider logo. Commenting the HTML code fixed the build.

    While I was there, I had a look at the CIDER logo I create, adding ~svg-components/cider-logo~ to the dashboard page.  Starting the project with ~lein ring server~ I saw that one of the SVG paths of the logo was missing (the left side of the glass).  So copied the path from the original HTML code and put it into the Clojure Hiccup code.  The path is now showing, however, it does seem to need tweaking a bit, as the top curve is missing as is a little of the bottom.  I will fix another day and then possibly use it for

*** Preparing for study group: trying out compojure-api
    Metosin are a very active company in the Clojure community running a number of events and publishing a lot of content and libraries for Clojure development.  Possibly the most used library is ~clojure-api~.

    Create a new project using the ~clojure-api~ leiningen template.

#+BEGIN_SRC shell
lein new compojure-api my-api
#+END_SRC

Its also possible to include tests with your new project, by adding ~+clojure-test~ or ~+midge~ as an option to the ~compojure-api~ leiningen template, for example:

#+BEGIN_SRC shell
  lein new compojure-api my-api +clojure-test
#+END_SRC

The project this template creates is relatively simple in terms of dependencies in the project.clj file

#+BEGIN_SRC clojure
  (defproject my-api "0.1.0-SNAPSHOT"
    :description "Experimenting with the compojure-api"
    :dependencies [[org.clojure/clojure "1.8.0"]
                   [metosin/compojure-api "1.1.11"]]
    :ring {:handler my-api.handler/app}
    :uberjar-name "server.jar"
    :profiles {:dev {:dependencies [[javax.servlet/javax.servlet-api "3.1.0"]
                                   [cheshire "5.5.0"]
                                   [ring/ring-mock "0.3.0"]]
                    :plugins [[lein-ring "0.12.0"]]}})
#+END_SRC

Interesting things to note are its using the ~lein-ring~ plugin, so we should run the application with ~lein ring server~.  When we want to deploy the application then we should use the ~lein ring uberjar~ command to create an uberjar (a java archive file that includes our Clojure application and the ~clojure.core~ library, so we can just run it as a java library).

In the ~:dev~ profile, dependencies include [[https://github.com/ring-clojure/ring-mock][~ring/ring-mock~]] library to help us test our server-side web application.  I'll probably cover testing a web app in a follow on broadcast.  There is also the [[https://github.com/dakrone/cheshire][~cheshire~]] library to help us work with JSON data in an efficient way.

* 20190221 Coach training
  Updated the coach training presentation, borrowing some slides from the ClojureX talk Yolina and myself gave in 2017.

  [[https://docs.google.com/presentation/d/e/2PACX-1vR_RYp1Vq9O75hmjG-SWRjtr8zezF8CUXicIOSkJqJf-U512u9E7SZm0UCzcIxqbia1VWObchTx9e-L/pub?start=false&loop=false&delayms=3000][Published presentation]]

  Tried to get a Bluetooth headset working, one I bought for the Playstation 3 a long time ago.  It would not pair with my Android phone  and was not even recognised by the laptop.  So I had a look through Amazon and [[https://www.amazon.co.uk/Bluetooth-Upgraded-Handsfree-Wireless-Earpiece-Black-blue/dp/B07GSPTBM9][found a suitable Bluetooth headset earpiece with microphone]].  Although I have wired headset with microphone for the broadcasts, it is useful to have a bluetooth single ear headset (ear piece really) for presentations.

  Cleaned up the kitchen and ordered [[https://www.amazon.co.uk/Pyroflam-Borosilicate-Clear-Steamer-Basket/dp/B003C1NH36][3 glass steamer baskets]] to fit with my ceramic pots.  If all goes well I can get rid of the metal steamers which build up limescale very easily.

*** Thoughts for today
    Its nice weather so time to get back out on the bicycle again.  Took the Brompton into London for the ClojureBridgeLondon coach training session.
** Activities
*** Coach training
    Caught up with David from Signal to discuss the running of ClojureBridge on the day and everything is in place for the event.

    Updated the coach training presentation, using some of the content from the talk I did with Yolina on how to run a ClojureBridge event.

    Broadcast the coach training live onto YouTube using the LiveBroadcasts and Google hangouts, all seemed to go well and the  [[https://www.youtube.com/watch?v=cZdo_vYvd8M][broadcast recording]] is up already.

* 20190220 Consolidate journals
** Thoughts for today
   The UK government sees to be lost, 3 more Conservative MPs have left the party, I wonder how many more will join them.

   Took the cats to the Vets for the annual checkup. They are a little over-weight but then it is still winter.  Mowgli was quite stressed today, which is a bit unusual.  I bought some new higher quality dried cat food and as I got two 7kg bags they gave me a 12kg storage tub for free (I shall have to get at least one more tub I think).

   Keeping up my healthy vegan diet today with Thai black rice and chickpeas.  Both were slow cooked yesterday, so quickly heated them in the ceramic pan and added a little balsamic vinegar

** Activities
*** Merged Journal repositories
    Merged the 100 days of Clojure journal with 2019 developer journal.  I had not committed any entries in the developer journal repository, so it was easy just to drop them into the existing 100 days of Clojure repository (after I renamed it and cleaned it up).

* 20190219 ClojureBridgeLondon editor guides & Bootstrap
** Thoughts for today
   The documentation for Cursive feels a bit sparse
** Code
   - [[https://github.com/ClojureBridgeLondon/workshop-content-gitbook/commit/81ab2952634ddcda7df8b8bc59e016761df4cdc4][Updated Proton user guide]]
   - [[https://github.com/ClojureBridgeLondon/workshop-content-gitbook/commit/9eaf20660f433a65e5f5470fb24de807592fa1d6][Added quick Cursive install guide]]
   - [[https://github.com/ClojureBridgeLondon/workshop-content-gitbook/commit/94084e52cc0ea4f9859fe621c708b6b37a9aaf31][Completed the Spacemacs install guide]]
** Activities
*** Updated ClojureBridgeLondon user guides
- Atom and Proton - configured styles for Atom using ~.atom/styles.less~
- Completed Spacemacs - added table of questions to answer when first running Spacemacs

*** Bootstrap codecadamy
    [[https://www.codecademy.com/courses/learn-bootstrap/l][Bootstrap codecadamy free course]]

    I have a better understanding of breakpoints and setting different column widths for based on device size.  This will be useful for the Clojure study group website, where the Bootstrap carousel was displayed quite squashed on a tablet form factor.

*** Updated Spacemacs
 Issue with org-mode Easy templates - tab not completing ~<s~ but indenting instead.  Could be due to my aggressive intending.  Disable that for org-mode?  Or just enable it for clojure & lisp.  Updated to latest Spacemacs and Emacs packages fixed the problem (seems to be a change in org-mode, so upgrading has fixed it)

*** Org-mode syntax
 https://orgmode.org/worg/dev/org-syntax.html
 - noted that a single ~*~ surrounding text makes it bold.

* 20190218 ClojureBridgeLondon
  Started updating Atom and Proton install and user guides. Trying to figure out how to set font size for Atom UI components (tab-bar, status-bar and tree-view), preferably in some configuration file.

  Took a quick look at [[https://www.codecademy.com/courses/learn-bootstrap/l][Bootstrap codecadamy free course]].

* 20190217 Ring and Compojure fun
  Continuing to explore the finer details of Ring and Compojure and updating [[https://practicalli.github.io/clojure-webapps/][Practicalli Clojure Webapps]] update

** Code
   - [[https://github.com/practicalli/clojure-webapps-content/commit/aa2a14d0f72be11ea9f4efd0d6f2fdf11eea5973][Updated section to callouts syntax]] and 7 other similar commits

* 20190216 Ring and Compojure fun
** Thoughts from today
   Its very interesting to start from the real basics of building a website in Clojure, without using any templates.  It also gave me an opportunity to update my [[https://practicalli.github.io/clojure-webapps/][Practicalli Clojure Webapps]].

** Code
   - [[https://github.com/practicalli/clojure-webapps-content/commit/a5c5ebacf9d5dfd11b394b2041d25a1c76ea60fd][Updated gitbook plugins and description]]
   - [[https://github.com/practicalli/clojure-webapps-content/commit/dcfc9d37714054216404f7be74fd2c02b592a6ca][Added the webpage style for practicalli books]]
   - [[https://github.com/practicalli/clojure-webapps-content/commit/bf5ef4a62bb9694b1ede7d0e7f472d4958ffaec6][ring version 1.7.1]]
** Activities
*** Update Practicalli Clojure WebApps
    Not many updates to [[https://practicalli.github.io/clojure-webapps/][Practicalli Clojure Webapps]] since October 2016, so although the main concepts have not changed, the library versions were quite behind so have been updating and testing them.

*** Running Ring application from Spacemacs
    Setting the ~:main~ keyword to a namespace will set that namespace when running ~cider-jack-in~, ~, '~.

    Evaluating the functions in the namespace allow them to be called.  Setting the ~:main~ namespace does not automatically load the functions of that namespace into the REPL.

    Call the ~-dev-main~ or ~-main~ function to start the jetty application server and load in the Clojure app.  The webapp is now available on localhost on what ever port was specified.

    As jetty is a continually running process, the REPL will continually be running (you can see from the moving === in the REPL buffer mode line).  This may be one reason that its more optimal to run the Jetty process externally (~lein run~ or ~lein ring server~) and just include the ~wrap-reload~ middleware to inject new versions of the code into the running jetty service.

* 20190213 Discussing a new opportunity
** Thoughts for today
   Met up with very interesting people to talk about building a Clojure startup

   Discovered my new favorite dish at Wagamama, the [[https://www.wagamama.com/our-menu/vegan][Vegatsu curry]] ([[https://veganuary.com/blog/vegatsu-vegan-version-wagamamas-iconic-katsu-curry/][review]]).  Its just like a Chicken Katsu curry, but vegan and even tastier.  I had tried the other vegetarian version of the Katsu curry, but it wasnt that nice.

* 20190211 Clojure dojo and YouTube API hacking
** Thoughts for today
   Using the YouTube Java SDK is a reminder of how redundant some Java code can be.
** Code from today
*** Asked Christian for the code
** Activities in detail
*** Setting up a Google account for API hacking
    I dont really want to use my email account for hacking on the YouTube API, so I created a hackingwithclojure Google account.  I also created a Chrome profile to make it easier to manage logins for multiple Google accounts.  It seems you need to create a project on the Google console to get started, so a new Chrome profile will be very useful.

*** Google API overview
    There are lots of APIs but we do not need them all.  For hacking with the YouTube API, we only need
**** YouTube Data API v3
     The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.
     https://developers.google.com/youtube/?hl=en_GB

**** YouTube Analytics API
     Retrieves your YouTube Analytics data.
     https://developers.google.com/youtube/analytics/?hl=en_GB

**** Freebase API
     Acording to the
*** Accessing YouTube API's
    Followed the article [[https://developers.google.com/youtube/v3/getting-started][YouTube API Data Overview]] and created a project in the [[https://console.developers.google.com/][Google Developers Console]].  A project is a grouping of API's from Google, so you can tailor each project to only include the API's you need to use.

    Created a project called youtube-data-api (it seems to take a while to create the project).  I think the UI just stalled, as I clicked on the notification in the Console and it took me to the details page of that project.

* 20190210 More workshop footage and PolyBius videos
** Thoughts for today
   Taking a break from code and putting together move videos to share on YouTube.  Also have the most successful go at PolyBius, getting close to 10 million points and getting much further in the levels that before.

   [[https://www.youtube.com/watch?v=SjFoHZXt9Zw][Archive: Clojure workshop JAX London 2015]]
   [[https://www.youtube.com/watch?v=uUBuem-GV3U][Polybius - Levels 1 to 9 (incomplete) - flashing imagery warning!]]

* 20190209 Clojure study group - functional composition
** Thoughts for today
   Had a good week of heads down on Clojure coding, updating many 4Clojure challenges with higher abstractions of code.  Rounding off all this coding today with functional composition and exploring the workings of the ~comp~ function.

   Converted several hours of video footage from my earlier clojure workshops and started publishing them on YouTube.

   Found the **Share** button on my PS4 controller which lets you record and share the footage from your game play.
** Activities
*** Clojure study group - functional composition
    broadcast discussing functional composition and explaining the workings of the ~comp~ function.  Also revisited a few of the 4Clojure exercises and used ~comp~ as one possible answer.
   https://www.youtube.com/watch?v=dhGAXISqra8

   [[https://gist.github.com/e703478b4e4dc2a20a86a4cd8a143343][Code examples from the study group]]

*** Archive workshop footage
    Found video footage recorded by my GoPro camera of several Clojure workshops given at conferences.
    [[https://www.youtube.com/watch?v=DssQg6rg-JQ][Devoxx uk 2017 clojurescript workshop part1]]
    [[https://www.youtube.com/watch?v=MJXQhVTdzQ4&t=3426s][Clojure - Thinking Functionally workshop at Devoxx UK 2016]]
    [[https://www.youtube.com/watch?v=R-VDPOAtgtM&t=610s][Archive Footage: Agile workshop - DesignIt, BuiltIt conference - part1]]

*** Recording Playstation4 games
    The Playstation4 controller has a Share button, well I say button, actually is a tiny recessed button next to the trackpad.  Although this button takes some skill to be able to press, it can be used to share and record video from the PS4.  So as I play my current favorite game, PolyBius, a psychodelic shoot-em-up style game that has an obsession with cows, I can record my games and share them on YouTube or broadcast them on Twitch.

    In the Playstation4 settings, I linked my YouTube and Twitch accounts (the Twitch link UI being much nicer to use that YouTube).  Now when I press the **Share** button on the PS4 controller I get a menu that will allow me to share the current video (or any video I have taken) with YouTube.

    To record game play, I can simply double press the **Share** button.  I say simply, pressing this button once is a bit fiddly, twice is even more so and trying to do this when I am wearing the Virtual Reality headset proved almost impossible at first (because I cant see the controller or my thumb.  After a bit of practice I eventually got the hang of double pressing the **Share** button.  I cant day double-click, because the button makes no sound when you press it.

    I published a test video (with really bad game play) up to YouTube to see how well it all worked https://www.youtube.com/watch?v=4CgWUA4GazI

* 20190208 4Clojure write up continued
* 20190207 4Clojure write up continued
* 20190206 4Clojure #53 update
** Thoughts for today
   Continuing to write up 4Clojure exercises as a way to help others understand my thought processes as I go through solving each of them.
** Code for today
*** 4Clojure #53 update
*** [[https://github.com/ldnclj/londonclojurians.org-content/commit/6856eff451bac1b55faa648a69ebc7019461147c][LdnClj website - how to run a clojure dojo]]
** Activities today
*** Writing up the approaches taken for 4Clojure #53
    I left the solution to 4Clojure #53 as solved a while ago, using partioning and filter functions as a nice abstraction over the loop recur approach.

    I never did the the loop recur approach to work and as it was bugging me, I decided to fix it.  I have become comfortable using the CIDER debugger, `, d b` in Spacemacs, so I instrumented the loop recur solution and identified the bug fairly quickly.

    It turns out the bug was pretty trivial, as I was trying to count the value of the temporary-sub collection, however, I had neglected to return the new temporary-sub value as a collection in the ~cond~ statement.

    Running the fixed code with the other tests showed that the 3rd test failed.  The loop recur didnt return the last value added to the sub-collection as the test for the empty collection terminated the loop too soon.  Adding a nested if statement to put another check of count for the temporary-sub and sub-collection returns the correct result.

    The final 4Clojure test still failed though, so I swapped the nested if statement for a cond.  I kept the conditions from the two if statements and added a third to return an empty vector, ~[]~, if the temporary-sub and sub-collection were both the count of 1.  With this last change, the code successful passes all the 4Clojure tests.

    I was please to have got a working version of the code using loop recur.  Although I would not use this approach in production, it is a useful way to demonstrate the different levels of abstraction in Clojure code.  It also clearly demonstrates that higher levels of abstractions can make Clojure code much more elegant and easier to work with.

*** Wrote a new guide on running a Clojure dojo
    We have some new uSwitch people helping out with the coding dojo events, so I wrote much clearer details on [[http://www.londonclojurians.org/coding-dojos/how-to-run-a-london-clojurians-coding-dojo.html][how to run the event]].

* 20190203 Clojure study group
** Thoughts for today
   Another Clojure study group, this time covering Sequences in Clojure.  We also walk through the solutions to 4Clojure exercises #23, #24, and #25.

   https://youtu.be/vehRrNqgVbQ

* 20190202 Clojure Study group
** Summary
   Posted the study group video to the #announcements channel of the Clojurians Slack community.  Have got quite a few more subscribers to the channel now.

   Broadcast covered sequences and the 4Clojure challenge #23 - reverse a sequence

   Fixed my Github personal access token for whitestar2, configuring the token to be able to create Gists.  I think the token created by Gist.el was overwritten by Magithub in the ~.gitconfig~ file.  For some reason neither access token had access to create Gists.

** Code from today

* 20190201 Coaching in Wagamama
  Coaching in Wagamama, meeting up with Brian at 10.30am and working through to nearly 5pm.

  Horrible weather outside so just took the train.

** Coaching
   Fixed Spacemacs setup with Magit and Github.  Needed a new SSH Key.

   Discussed some project ideas.

   Worked on 4Clojure challenge #62 - re-implement iterate function
