#+TITLE:       Developer Journal - March 2019
#+AUTHOR:      John Stevenson
#+DATE:        <2019-03-01 Fri>
#+EMAIL:       john@jr0cket.co.uk
#+LANGUAGE:    en


* 20190317 - Clojure study group - API part 3
** Thoughts for today
   Had a good clojure study group, going through how to create an API for a Game scoreboard.

   Big tidy up and clean of the house as my friend Lisa was coming for a visit.  The house feels huge now.

** Code commits
*** [[https://github.com/practicalli/game-scoreboard][practicalli/game-scoreboard]]
** Activities in detail
*** Creating an API for a game scoreboard
    Walked through the creation of a game scoreboard using the Leiningen clojure-api

* 20190316 - prepare for study group
** Thoughts for today
   Work up early (5am) with a big coughing fit and felt exhausted.  I really felt bad so decided to postpone the study group until Sunday.  This will also give me time to tidy up the code for the study group and add better explanations.

   Helped one of my students from the study group with a bug in their code.

** Code commits
*** [[https://github.com/jr0cket/advent-of-code-2019/commit/d92af1a44c5aa838f2e58567f3f477ec8671633a][Updated clojure.core.matrix require statement]]
** Activities in detail
*** Fixing a bug for Waffles Advent of Code
   Helped Waffles to fix a code bug, there was a typo that too a while to spot in the :require of the namespace.  Waffles had put ~clojure/core.matrix~ instead of ~clojure.core.matrix~ for the ~net.mikera/core.matrix~ library.  Its a confusing namespace as it makes you think the matrix library is part of clojure.core, which it is not.

* 20190315 - Interview in Cambridge
** Thoughts for today
   Took a bit of time to get myself together this morning, still tired from the flu I guess.  I got myself going and used the Brompton and trains to get to Cambridge with lots of time to spare.  I enjoyed cycling around Cambridge, it is a very nice town (or is it a city?) and much as I remember it.  I have been there for quite a few conferences, mainly Agile Cambridge, where I spoke a few times.  I also did a talk for Functional Cambridge conference on Leiningen.

   The [[https://nextjournal.com/][Next Journal project]] is a Clojure version of Jupiter notebooks, except it also supports several different languages rather than just python.  One of the developres, ..., gave a presetation on ... at ClojureD.  The project looks very interesting, so I will have a go with the getting started guide.is a Clojure version of Jupiter notebooks, except it also supports several different languages rather than just python.  One of the developres, ..., gave a presetation on ... at ClojureD.  The project looks very interesting, so I will have a go with the [[https://nextjournal.com/help/quickstart][getting started guide]].

** Code commits
*** .
** Activities in detail
*** Cambridge interview
   The interview itself seemed to go very well.  It was very interesting to meet and understand the dynamics of the core team.  I met with the 3 founders who had quite different personalities but seemed relatively complementary.  I also met the two main developers and we had lots of interesting conversations.  I did seem to be the one getting asked all the questions, but this was to be expected as they have a lot of questions about how to grow their team and their business.  That is after all what the role would be there to help with.  The interview was getting on for 3 hours although never felt uncomfortable to me.  There may have been one or two questions I deflected and detracted from, but I think that was okay.

   My main concern about the role is moving to Cambridge with brexit uncertainty ever more chaotic.  I dont think I am comfortable making a decision until we have either a peoples vote or article 50 is withdrawn.  If brexit remains uncertain, I may only feel comfortable in commuting, but that is going to be 2 hours door to door each way, so 4 hours commuting each day.  That doesnt seem feasible unless the founders are okay including some of that time as work time.  Even if they are, that could cause tension in the team if I start late and finish early.

   I have not yet seen the product they are building although have had assurance that it is proper AI work and not just the basic stuff that has been around for a few decades.  If I get a strong enough afinity to the product, that could help override the concerns about relocating.

* 20190314 - Prepare for Cambridge interview
** Thoughts for today
   Still have a few after effects of the flu, but have a lot more energy now.  Hmm, I spoke too soon and the flu caught up with me again.  I did sort out some of my code and pushed some more commits, but still a lot to organise.

   Had a great conversation with a new friend called Lisa.  Very enjoyable chatting with her and we seem to have similar thoughts on life.  It will be interesting to see where this goes.

** Code commits
*** .
** Activities in detail
*** Using Google Colab
    Found some interesting tutorials to help get started with Google Colab.
    - [[https://colab.research.google.com/][Google Colab]]
    - [[https://medium.com/dair-ai/primer-for-learning-google-colab-bb4cabca5dd6][Primer for Learning Google Colab]]
    - [[https://towardsdatascience.com/getting-started-with-google-colab-f2fff97f594c][Getting Started With Google Colab]]
*** Preparing for Cambridge inteview
    Reviewing examples of my coding as they company said they would like to see code I am particularly proud of.  As a lot of the Clojure code I am able to share is aimed at teaching people Clojure, I am unsure if its of the level they are looking for.  All of the code I have done for work is not sharable unfortunately.

    Some examples I have come up with include
**** ClojureBridgeLondon workshop content
    [[https://clojurebridgelondon.github.io/workshop/][ClojureBridge London website]]
     Discuss some of the challenges of teaching people a new language, especially when there is mixed experiences in the room.
     - creating separate learning paths: simple challenges, responsive website, react style website (deployed on GitHub pages).
**** Clojure web apps
     -[[http://practicalli.github.io/clojure-webapps/][Practicalli Clojure WebApps]]
**** 4Clojure discussions
***** #53 longest sub-sequence
      Quite a procedural challenge so interesting to see how its done in a more functional way.  Using the Clojure debugger to step through the code helps demonstrate the different approaches.

**** Most common word
     [[file:~/projects/clojure/clojure-through-code/src/clojure_through_code/hhgttg-book-common-words.clj::;;%20Example%20of%20threading%20macros%20and%20the%20use%20of%20a%20connected%20REPL%20to%20give%20fast%20feedback][HHGTTG - Most Common word]]
**** SVG library
     - Monitoring dashboard
     - SVG component library and examples

**** TicTacToe Reagent & SVG

*** Linking to files in org-mode
    Linking to files, such as other source code files, is just the same as adding other links.  In Spacemacs that is ~, i l~, adding the path and filename and then the name of the link.

    You can make this easier by getting a link to any file using ~org-store-link~ function, or ~SPC a o l~ (app, org, store-link).  This will get the path and filename of the file as well as append

    ~org-insert-last-stored-link~ will add a link to the file using the information from  ~org-store-link~.

    ~, i l~ will also insert a link and you can use ~C-y~ to paste the link from ~org-store-link~

* 20190313 - Interviews and Machine Learning study group
** Thoughts for today
   Had a really good time at an interview today, very friendly people and it never really felt too difficult.  Hopefully I didn't give them any remnants of my flu.

   Worked on the info-graphic for how to run a ClojureBridge London event.  I had drawn up the design for the info-graphic on the wall at home (well a dry-wipe sheet on the wall).

   Caught up with a volunteer who wanted to be an organiser for ClojureBridge London.  Went through the organisation tasks in about 20 minutes, using the info-graphic (which worked pretty well).  Discussed doing a `live evaluation` session for the next event, taking an existing code base and explaining what it does by evaluating the code and showing the results.  Also discussed having separate trails to follow based on what students wish to try, which would include a learning path to built a website from scratch as well as create enhancements for a new website

   Attended the ML Study group and learned about [[https://colab.research.google.com/][Google colab]], an online Jupiter Notebooks tool that also supports GPU powered calculations.  It also means you don't have to install lots of python libraries and versions on your laptop.

* 20190312 - final day of flu
** Thoughts for today
   Hopefully this is my final day of flu.  I felt really horrible this morning but mostly better this afternoon.

   UK politics is still a mess but at least the terrible withdrawal deal has been voted down a second time.

** Code commits
*** .
** Activities in detail
*** Stopped using Chrome Beta
    Switched back to Chrome as ironically Chrome Beta just didnt work with Google maps

    Added any useful pages to the TODO section at the top of this journal.

* 20190311 - missing uSwitch Coding dojo - flu
** Thoughts for today
   I still have a bit of flu, but think its just the after effects now.  Will cycle on my brompton into uSwitch and see if that makes me feel fitter.  Actually, I am still feeling a bit rubbish, so I might get the train into London and cycle back.  Update:  I still feel very tired and unable to concentrate, so will have to miss the coding dojo

   Updated some 4Clojure exercises instead of attending the coding dojo.

** Code commits
*** 4Clojure #27 - Palindrome detector
*** 4Clojure #29 - All the CAPS
*** 4Clojure #30 - Compress a sequence

** Activities in detail
*** 4Clojure exercises - updating discussion
*** Updated org-mode TODO state colours (faces)
    I am using TODO states in org-mode much more often now, especially at the head of this developer journal, to ensure I get essential things done and I dont forget about less urgent things I'd like to do.  I didnt like the colours I was using, so thanks to https://en.wikipedia.org/wiki/Web_colors I made them more colourful (without being too strong) using the X11 color names.  This may not work on terminal Emacs if X11 is not installed, but you could use simpler names for the colours.

    The todo state colours were defined in the ~dotspacemacs/user-config~ section of ~.spacemacs~

#+begin_src elisp
(with-eval-after-load 'org
    (setq org-todo-keyword-faces
         '(("todo" . "SlateGray")
           ("doing" . "DarkOrchid")
           ("blocked" . "Firebrick")
           ("review" . "Teal")
           ("done" . "ForestGreen")
           ("archived" .  "SlateBlue"))))
#+end_src

    Re-evaluate the ~.spacemacs~ file using ~SPC f e R~ and the changes will take effect immediately.

    When moving through TODO states in an org-mode file, e.g. using ~M-<right-arrow>~ or ~M-<left-arrow>~, each state has its own colour.

*** Fixing org-mode 9.2 easy templates in Spacemacs develop
    Up until recently, typing ~<s~ and pressing ~TAB~ would create a source code block in org-mode.  However, since org-mode 9.2 some of the formatting has changes.  Although Spacemacs seems to be okay in general, it is the org-reveal (ox-reveal) package that is not compatible and causing errors.

    Several issues have been raised on the Spacemacs issue tracker on GitHub, however the [[https://github.com/syl20bnr/spacemacs/issues/11935][Request: Use org-re-reveal instead of stale org-reveal]] issue has a fix that worked for my ~develop~ branch of Spacemacs (updated today: [2019-03-11 Mon]).

    Start by disabling org-reveal via the org layer options.  Edit ~.spacemacs~ and configure the org layer as follows

#+BEGIN_SRC emacs-lisp
(org :variables
     org-enable-reveal-js-support nil)
#+END_SRC

    If you do not wish to use org-reveal (or org-re-reveal) to create HTML5 style web page for presentations, then you can just stop here.  You can create source code blocks in org-mode using ~, b d~ to call the ~org-babel-demarcate-block~

| Keybinding | Description                                                                                                               |
|------------+---------------------------------------------------------------------------------------------------------------------------|
| ~i b~      | select from a list of block types                                                                                         |
| ~b d~      | create a code block for a specific language - helm menu to select language.  ~C-c C-,~ in Emacs.                          |

    To generate presentations, go to just below the layer definitions in ~.spacemacs~ and add ~org-re-reveal~ to the ~dotspacemacs-additional-packages~ name.

#+BEGIN_SRC emacs-lisp
dotspacemacs-additional-packages '(org-re-reveal)
#+END_SRC

    Finally, in ~dotspacemacs/user-config~ tell Spacemacs to use the ~org-re-reveal~ package, after the org layer has loaded.

#+BEGIN_SRC emacs-lisp
  (use-package org-re-reveal :after org)
#+END_SRC

    So now I can use org-mode templates again and still generate presentations (although I need to test generation still works with my existing org-mode files).

* 20190310 still have flu
** Thoughts for today
   Feeling like crud most of the day.  By the evening I managed to update this journal with a few additional updates.

   I cancelled the Clojure study group this weekend, as I just couldn't focus because of flu.

* 20190309 still very flu-ee
** Thoughts for today
   Still full of flu so caught up on lots of sleep.

** Interesting articles
*** [[http://clojure-goes-fast.com/blog/clojures-slow-start/][Clojure's slow start]] - deconstruction of what happens during startup of Clojure, Leiningen and Boot
*** [[https://github.com/OlegIlyenko/clojure-icons][Clojure logos]] - nice svg and png Clojure logos
** Activities in detail
   Nothing much of merit, simply catching up with Clojurians slack channels.

   I like the [[https://github.com/ogdenwebb/emacs-kaolin-themes][kaolin themes for Emacs]], they are very colourful and have a good contrast so should be good for demos and screencasts.  I simply added ~kaolin-themes~ to the ~dotspacemacs-additional-packages~ configuration in ~.spacemacs~.  Then after reloading the configuration, ~SPC f e R~, I could select these new fonts via ~SPC T s~

   Interesting [[https://github.com/AndreaCrotti/yasnippet-snippets][collection of yasnippets from Andrea Crotti]], including a range for [[https://github.com/AndreaCrotti/yasnippet-snippets/tree/master/snippets/clojure-mode][Clojure mode]].  TODO: Evaluate the clojure-mode snippets and see if any are missing from Spacemacs / CIDER.  Consider pull requests if there are useful ones missing.

* 20190308 Call with AI startup
** Thoughts for today
   Had a very interesting chat with the CEO of an AI driven education platform.  An initial conversation seemed quite promising and we had general agreement on approach to a CTO role.  The biggest factor for me is that it would require relocation.  Although I like the new location, it is the uncertainty of Brexit that adds to the risk of moving.  Having a Cambridge location will also be a challenge to attract developers out of London, even more so if Brexit gets worse (especially if the UK GBP drops further against the Euro) and EU developers decline to come to the UK.  The opportunity is worth investigating, so I have booked a train ticket (trainlinenext) Friday to go and see the directors.  I got an all-day return as the meeting time had not been set.  I also found a potentially interesting talk at the [[https://www.eventbrite.co.uk/e/gene-eating-the-truth-about-diets-tickets-54923010202][Cambridge University on Genes and diet]].

   Found an interesting learning resource: [[http://iloveponies.github.io/120-hour-epic-sax-marathon/][Functional Programming in Clojure MOOC]]

   Still full of flu, so went to bed.

* 20190307 Flu started
   Yes, my shelving finally arrived.  It seems the two packages were not held together very well, which may have caused the delay (or it could have been due to EU countries practising Brexit no-deal scenarios).

   I had applied for Universal Credit, mainly to see what the experience was.  I was told my claim was closed today, as I had too much in savings.  I was not surprised.  Applying for Universal Credit did take a bit of time - trying to figure it its the only option took time, as I wasnt able to claim for job seekers allowance online.  The online application did take about 20 minutes once I had read all the right documemtation.  I then had to verify myself, wich I chose to do using the Post Office mobile phone application.  The app was used to scan my current passport and take a very dodgy picture of myself (bad hair day).

   It does seem that its the people on existing benefits are the ones who are having the biggest issues, as new claims seem to be fairly straight forward (and less of a mess than previous multiple approaches).  The assessment beyond those only claiming for unemployment does sound a real mess though and the claims for those unable to work because of a disability seem worse than cruel.

* 20190306 Lunch with prospective company
** Thoughts for today
   Reflecting on my experiences for the last 22 years in the software development industry led to a nice little journey down memory lane.  I have been very lucky to have lots of different experiences, most have been positive although there have been lots of life lessons.

   Whilst thinking about all the companies I have worked for, there have been quite a few involved in mergers and aquisitions, many more than I remembered.  If fact most of the companies I have worked for have been either aquired by another company or have aquired other companies.

*** Objective Alliance
   My first role after Newcastle University was at a very small consultancy company based in Amsterdam called Objective Alliance.  This company had an interesting tag line: new and proven technology.  I was there for 3 years and in the last year they were aquired by a Dutch company that were doing what we called old but everywhere technology (COBOL mostly).  I didnt see much of the details of the merger, however, many of the technical staff did leave as it wasnt clear what our roles and direction would be.  I was on long term assignment in another part of the country (Neimegen, which was lovely) and so didnt see the day to day changes.  Just after finishing that assignment we an office party involving both companies and its there I realised I didnt really feel a part of the company.  In the end I decided to leave due to the combination of the merger (not knowing what was ahead), always being on assignment (not connected to the people I work with) and the language barrier (everyone worked in English and I had been caught up in the work that I hadnt set aside time to learn Dutch).

*** Valtech
   Next I worked for Valtech, another consultancy company in London, UK.  I worked there for a year and they didnt get aquired.

*** Proxicom
   I was head-hunted to a company called Proxicom who had recently aquired Clarity, a small technical design company, to bootstrap their expansion into Europe.  Proxicom was a USA based consultancy company that had seen rapid growth in the USA and wanted to bring that to London.  Initially we were working in separate offices, so there was not much integration between the teams.  Only if people were put on a project together would they have much chance for interaction.  After about 4 months we moved into some new offices together so there was a bit more chance to work with the technical team from Clarity.  For a few months it was a great chance to learn from each others very different skill sets.  I learnt to appreciate the complexities of front-end development.

  A few of us did come together and start to discuss working practices and how we could improve the quality of delivery at client engagements as well as capture lessons learnt.  We presented our thought to management and they created an Architects team (although we didnt care for the name, it did give us a chance to start working on improving practices and capturing lessons learned with many of the teams.

  After nearly about 9 months of working at Dimension data there was talk about an aquisition of the company but very little details.  Someone had mentioned Dimension Data (a South African company I had never heard of before).  A month later the whole company in the UK was brought together for a afternoon off-site meeting where we found out that we were just about to be aquired by Compaq (who to me were a company that made PC's).  There were some very surprised people in the room and it seemed a lot of concern about this aquisition.  Many people thought they would be made redundant or were concerned about being onwed by Compaq.  Reassurances were made about jobs as the process was explained over the next hour.  It was a warm room, perhaps because of the tension in the air.  The presentation also seemed to go on for a long time, perhaps just to calm people down through powerpoint attrition (the slides were very dry and hard to engage with.

  Within a week everything had changed.

  Rather than be aquired by Compaq, Dimension Data had come back to the table and wanted to aquire us.  Within a few days it was all arranged.  Its easy to think in hindsight that the Compaq deal was just to motivate Dimension data to get around the table and sign a lucrative (for Proxicom) deal.

  Within a few week of that, they were handing out redundancies...  They were incredibly generous redundancy packages, so I snapped one up straight away.

*** ObjectCore
    I had an opportunity to do some consulting work and so set up my own company called ObjectCore, unfortunately no-one aquired my company for 1 million dollars :smile:

*** Q&A Systems
    In 2004 I worked for what turned out to be a pretty doomed startup company, although looking at companies house it limped on until 2014.  They were never aquired, although we did get the Inland Revenue interested in our product.

*** Docucorp
    At the start of 2006 I joined a product company called Docucorp who were an American company that had aquired a UK company to drive sales of the product and provide technical pre-sales and technical consultancy.  By mid-2007 Docucorp had been aquired by SkyWire software, another American company rapidly expanding through many aquisitions.

    The fun didnt stop there as within about 4 months of being aquired by SkyWire, then SkyWire themselves were going to be aquired by Oracle.  In order to streamline SkyWire for the Oracle aquisition a dozen redundancies were offered along with a very nice package including career support.  I decided to take redundancy again as I want that keen on what SkyWire were doing and more concerned about Oracle.

*** Brit Insurance
    After a couple of months break and a well deserved break I was contacted by Brit Insurance, a company who I had worked for during my time at Docucorp.  The wanted me back because no one knew (or perhaps wanted to know) how to use the Docucorp system.  Not that I really knew that much, as there was an extreme amount of trial and error with all of it.  I took the role as it would be a straightforward choice and an okay salary (probably could have asked for more, as I would have been much cheaper than paying for me via Docucorp as a consultant).

    By the start of 2010 Brit Insurance was under performing its competitors by a long way, arguably to the massive redundancy in the the application development teams.  There were 3 main divisions for the business and each had successfully argued that they should have their own development teams (and project managers) even though most of the IT solutions were doing pretty much the same thing.  After asking the CTO at that time about what the differentiator was for Brit Insurance, I was surprised to be told that their was none, specifically "its all just insurance".   That was when I decided to make my exit.

    Within 4 months of leaving Brit Insurance was aquired by Fairfax Financial Holdings and quickly streamlined the company.  The IT department went from around 100 people to around 10 people.

*** The rest of my career has been more stable
    In terms of being aquired by companies, very little else has happened in my career to date.

    I worked for Atlassian, but left before they went IPO.  I was only there for a year or so and would not have really benefited from that event.

    Salesforce was very interesting.  They were already a public company and it really did give me a good insight into the impact that unexpected quarterly results can have.  The first time I noticed this was the aquisition of Exact Target in 2013 for $2.5 billion and budgets were put on hold very briefly.  A much bigger impact was the UK advisory referendum in 2016 that narrowly voted to leave and caused the UK currency to drop in value massively against the USA dollar.  This immediately killed the budget for our team for the next 3 months and impacted levels for much longer.  There are a number of [[https://www.salesforceben.com/top-5-salesforce-acquisitions-time-now/][large aquisitions by Salesforce over the last 5 years]] that I assume has required a little forward planning.

    After Salesforce I took a job at Citi group.  They had mostly recovered from the financial crisis by the time I had joined.  I found Citi so big (220 million employees) that I didnt really know about any aquisitions they did.

    So my career has seen some very interesting events over the years.  I wonder what will happen over the next 20 years or so...

* 20190305 ClojureBridge London disqus feedback updates
** Thoughts for today
   Wondering when my shelving that is coming from Germany will arrive.  As its not Amazon Prime, then the tracking is very vague.  Switched to tracking via the GLS website which then gave me a code to track on Parcelforce.  Its not going to arrive today :unamused:

** Code
   Just markdown updates today.
** Activities
*** Updating ClojureBridge from Disqus feedback
    7 pieces of feedback were recieved via disqus form at the bottom of each page of the workshop content.  All the issues raised have either been fixed or a ticket on the [[https://github.com/ClojureBridgeLondon/workshop-content-gitbook/projects/1][GitHub project for the workshop content]] has been raised.
*** Updated the Practialli Spacemacs install page
    A comment on the disqus form for the Spacemacs install page said about adding a link to download Emacs.  Added a link to the Emacs install section and the "before you start" section to ensure that people read the pre-requisites.

* 20190304 Initial interview
** Thoughts for today
   Feeling much better after having a great conversation with a prospective company today.  Gave me a chance to reflect on what I want to do next.  This role and company seem very promising.

   Still feeling a bit down about an accusation that I was trying to commercially exploit ClojureBridge London.  I am still in a bit of shock about that accusation.

* 20190303 Clojure Study Group
** Thoughts for today
   Had an okay Clojure study group, although generally feeling a bit down because of the incident on Friday.

** Code
4Clojure solution discussions

** Activities

* 20190302 ClojureBridge London workshop
** Thoughts for today
   Stayed in the background today to avoid any further acusations of trying to exploit ClojureBridge London.  I tried my best to ignore this quite hurtful accusation and not let it affect my interaction with the attendees.

** Code
*** New Project: Build a ClojureBridgeLondon website
   Some sample project code for a ClojureBridge London website, to be used as the basis of a project for the students
   https://github.com/ClojureBridgeLondon/clojurebridge-london-website-example

** Activities
*** Hack ClojureBridgeLondon Workshop content
   Some quick fixes for the workshop content and a bit of work on the ClojureBridge London Website project content.

* 20190301 ClojureBridge London Introduction
** Thoughts for today
   A very disturbing incident while I was trying to run the introduction for ClojureBridge London.  I was later accused of trying to commercially exploit ClojureBridge London.  Apparently broadcasting the introduction to those few who who couldn't make the event was beneficial commercially to me as a consultant.  However, I am not a consultant and have never had a consultancy role in Clojure or any kind of consultancy role since 2001.  The complaint continued to accuse my company, Practicalli, of benefiting from ClojureBridge London.  However, there is no such company and Practicalli is a collection of freely available books published by myself on GitHub pages to encourage others to learn Clojure and free tools such as Spacemacs.  The complaint moved on to exploiting ClojureBridge London for my own personal brand development.  This is not the case and was pretty devastated to hear that someone would make such an accusation or even think I would do such a thing.

   I do care that the ClojureBridge London event is run well and the experience is as positive as possible.  I hope that some of the students gain some insight into why our community loves developing with Clojure and I try to ensure the coaches have all the support and confidence they need for the event.

   I will think about why a person should consider that I have such ulterior motives with respect to ClojureBridge London and I will need to consider if I should continue being involved.  The person who made these claims is has said they will no longer be involved with ClojureBridge London or the London Clojure community as they have moved on to other things.  But I am concerned that others may have the same concerns, so will reach out to other people that have been active in the community to see what their view is.

** Code
  Mostly markdown content changes

** Activities
*** Content change for Friday intro of ClojureBridgeLondon
    Updated the Friday section to make it more engaging for the students
