#+TITLE:       Developer Journal - April 2019
#+AUTHOR:      John Stevenson
#+DATE:        <2019-04-01 Mon>
#+EMAIL:       john@jr0cket.co.uk
#+LANGUAGE:    en


* 20190424 more spring cleaning
** Thoughts for today
   Another break from the computer today

* 20190423 Codebar & CSS debug
** Thoughts for today
   Cooler weather again, so easier to focus on coding (although I did a pretty good job yesterday)

   Mood: started off quite low, did an hour of exercise and then felt okay the rest of the day.
** Code commits
*** [[https://github.com/ClojureBridgeLondon/landing-page-draft/commit/8edbdda2a9fedd26adb6f55e33942b10fe1be1cc][Added debug.css for visually debugging CSS styles]]
** Activities in detail
*** Checked clj-refactor still working
    There was a question on #spacemacs as to if clj-refactor was working (as they were experiencing errors when adding a project dependency).  I fired up a Clojure REPL in the ~clojure->code~ project and tried some ~clj-refactor~ commands.  Everything seemed to work, so reported this back to the slack channel along with my version of Leiningen, Java and Spacemacs (CIDER).
*** Visually debugging CSS
    Sometimes CSS errors are hard to see as you are looking at the results rather than the structure that the CSS is creating for you.  Listening to one of the videos on learning Bulma, the person was using a debug.css file to visually debug the structure of the CSS that looked very handy.

    This [[https://medium.freecodecamp.org/heres-my-favorite-weird-trick-to-debug-css-88529aa5a6a3][debugging CSS article]] shows how to create a ~debug.css~ file that will display a structured representation of the CSS.  When you need to debug, just include this file into the index.html page just like any other CSS style file.

#+BEGIN_SRC
<link rel="stylesheet" href="styles/debug.css">
#+END_SRC

    The CSS for the debugging is as follows:

#+BEGIN_SRC
*:not(path):not(g) {
    color:                    hsla(210, 100%, 100%, 0.9) !important;
    background:               hsla(210, 100%,  50%, 0.5) !important;
    outline:    solid 0.25rem hsla(210, 100%, 100%, 0.5) !important;
    box-shadow: none !important;
}
#+END_SRC

    There are newer versions of this [[https://gist.github.com/zaydek/6b2e55258734deabbd2b4a284321d6f6][debug.css file on GitHub Gist]] however only version ~0.0.1~ actually worked with the Leiningen project.  I did not understand if something in the code was required to make the ~[debug]~ work in the newer versions.

    Another approach is to add [[https://zaydek.github.io/debug.css][debug.css as a bookmark]] and then just use that bookmark to toggle debugging off and on again.  This could also be added as a button or switch on the page during development.

* 20190422 Bulma tutorial
** Thoughts for today
   Watch a tutorial on Bulma for some inspiration.

   Watched the last 3 episodes of `The Umbrella Academy`.  Fairly enjoyable although the some of the story-line was a little predictable.  I enjoyed most of the acting and overall plot
** Code commits
*** .
** Activities in detail
*** .

* 20190421 Bulma ClojureBridge London website
** Thoughts for today
   Thinking about the design of the ClojureBridge London website and how to make a good balance of engaging content and functionality.  A lot of experimenting to do.

   Started thinking about hiccup code generators for common elements, such as ordered lists.  However, could take this further and do this for higher abstractions such as navigation bars.  Then simply define common names for things in a data structure and pull that from the application state.
** Code commits
*** [[https://github.com/ClojureBridgeLondon/landing-page-test][ClojureBridgeLondon/landing-page-test repository]] - deployment repository (manually copied)
*** [[https://github.com/ClojureBridgeLondon/landing-page-draft][ClojureBridgeLondon/landing-page-draft repository]] - project source code

** Activities in detail
*** ClojureBridge London website with Bulma and Clojurescript
    Applying more styles from the Bulma CSS framework to create a responsive and engaging website for ClojureBridge London.  So far its not much more than a hiccup version of the current site, but it is helping generate ideas of things that can be more dynamic.

**** Resources
     - [[https://scrimba.com/g/gbulma][Free code camp course on Bulma]]

* 20190420 Maria.cloud @ Clojure Study group
** Thoughts for today

** Code commits
*** .
** Activities in detail
*** Maria.cloud animation and advanced stuff @ Clojure study group

* 20190419 More Gardening, more coding
** Thoughts for today
   Really hot today, had to be careful to not get sunburn whilst gardening.  The temperature is over 70 Celsius in my hotbox recycler.

   Mood: pretty stable today, no moments of euphoria or downers.

** Code commits
** [[https://github.com/jr0cket/spacemacs/commit/5d62aba7002ddffc23856e02cc2ddacf12e60471][Spacemacs PR - cider-undef keybinding]]
** Activities in detail
*** ClojureBridge London website - Figwheel main and Bulma
*** Spacemacs cider-undef keybinding
    Added ~SPC m e u~ keybinding to the ~clojure~ layer to provide a Spacemacs menu entry for the command ~cider-undef~.  The ~cider-undef~ function removes the symbol (i.e. ~def~ / ~defn~ name) under the cursor from the current namespace.  If there is not a symbol under the cursor, then you are prompted in the mini-buffer to supply a symbol name.

* 20190418 Gardening and Coding
** Thoughts for today
   Its a lovely day to be outside.  I started sorting out the garden

   Mood: still pretty good mood (not quite the euphoria of yesterday).  A few minutes low in the afternoon, but quickly regained.

** Activities in detail
*** nojekyll for jr0cket blog
    Added a ~.nojekyll~ file to the ~source~ folder of my Hexo powered blog for jr0cket.co.uk to minimise processing on the GitHub side (as it stops the content from being processed by the GitHub Jekyll service).

    Added ~include: - .nojekyll~ to the ~_config.yml~ file to ensure that the ~.nojekyll~ file is included during ~hexo generate -d~

*** Published blog for the ClojureX CfP
    Published the blog I wrote yesterday.  It was picked up by Planet Clojure blog roller once I set the category to ~clojure~ in the heading of the post.
*** Updating jr0cket DNS
    After publishing a new blog on jr0cket.co.uk I was getting warnings about mis-configured DNS.  It seems GitHub pages have changed the IP Addresses used for A records (which I currently use for redirecting http://jr0cket.co.uk/ bare domain to the GitHub pages site.

    With a bit of hunting I found the new IP addresses https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider

    I added 4 new A records to the DNS for the jr0cket.co.uk domain on Gandi.net and then deleted the two old A records.  Hopefully everything should work correctly when the change updates a a few hours.

    Ideally I should move away from DNS A record types to the ALIAS type (supported by Gandi.net) and then I can simply point the bare domain to jr0cket.github.io, as show in this article: https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-an-alias-or-aname-record-with-your-dns-provider

* 20190417 ClojureX committee and blogging
** Thoughts for today
   I woke up feeling great.  I think I got a pretty good sleep overall, but still had a bit of a weird dream before I woke up.  Got a lot of stuff done in the morning, shopping for fruit and veg in the afternoon and a Jurassic Park triple bill on Netflix.

   Mood: Early morning euphoria and excitement (for no particular reason)

   Cooking: chickpeans in wonderbag before bed.

** Activities in detail
*** ClojureX CfP draft review and blog post
    Finalising the ClojureX Call for Papers blurb with SkillsMatter.  I sent through an updated version of the CfP topics, as I didnt think it was clear enough as to what we were suggesting.  I didnt like there marketing speak and inaccuracy of the original prose so I suggested an an alternative.  This alternative is now the text of the CfP.

    I used the updated topics and alternative prose to create a blog on jr0cket.co.uk about the CfP, which I will publish tomorrow.

* 20190414 Practicalli Spacemacs updates
** Thoughts for today
   More spring cleaning of the office and its getting very roomy in there.

   Started working on a new ClojureBridge London website using ClojureScript, Figwheel-main and reagent.  As I was documenting that I added more content to the Practicalli Spacemacs guide, especially around the use of Magit.

** Activities in detail
*** .

* 20190413 Maria.cloud @ Clojure Study Group
** Thoughts for today
   Creating a Maria.cloud based curriculum for the next ClojureBridge London event.


** Code commits
*** .
** Activities in detail
*** Maria.cloud curriculum for ClojureBridge London
    - naming of files - is there a character limit? or some other limit to stop the files from showing?

*** ClojureScript site for ClojureBridge London website
*** Spacemacs: refresh gist list

* 20190411 Restart interview test
  I wasnt very focused a few days ago and mixed up the schedule for my technical interview.  So ended up rushing the solution and making a total travesty of it.  Starting from scratch today
** Thoughts for today

** Code commits
*** .
** Activities in detail
*** Devoxx 2019 volunteering
    Accepted volunteering for Devoxx 2019.  Emailed confirmation I can make all three days and supplied some suggested things I could volunteer for.

* 20190404 away from keyboard
* 20190403 Personal day
* 20190402 Ldnclj meetup - Blockchain
** Thoughts for today
  I received some sad personal news today, it has been waying quite heavily in the back of my mind. I am more than a little down about this.  Unfortunately I got caught up in that and was late setting off for an interview, then hit transport issues with the train.  Ended up not making the appointment unfortunately.

  Took the train home as I didnt have the energy to ride.

  Interesting question on creating stong enough passwords for symmetric encryption.  Daniel Compton recommended Diceware (Wikipedia), using several roles of a dice to create a number that is a lookup in a word list (e.g. The Electronic Freedom Frontier word list).  This gives a password of around half a dozen words separated with spaces, to create a very strong password.  Creating a website that generates these random passwords (in multiple languages) would be a great dojo and ClojureBridge exercise.

** Code commits
***
** Activities in detail
*** Presenting the meetup
    I put a brave face on things and introduced the speaker.  I am afraid I didnt do much of an introduction.

    It was an interesting journey across many subjects and really started to focus on specific topics once the audience engaged.  Some interesting projects were raised and could be talked about in further presentations.



* 20190401 Parliament vote round 2
** Thoughts for today
   Brexit is a disaster and the UK parliament is no longer fit for purpose.  Unfortunately, the UK parliament is elected by the UK population, which says very little good about them either...
** Code commits
*** Code interview challenge - local commit only
** Activities in detail
*** Short notice code challenge
    Cant share details, but I got a couple of coding challenges for an intervew Thursday Morning.  Had to drop a few things to try fit one in, but not much time.  Came up with some ideas of how I would like to solve the problem, but having tested the feasibility of those ideas.
